### ISSUE TITLE
/source endpoint results in a Server Error (500) 

### ISSUE THREAD

**Issue by hellerbarde** [qmk/qmk_api#10]
It happened while using the qmk configurator.

The Entry in the console looked like this:

jquery-3.2.1.min.js:4 GET http://compile.qmk.fm/v1/compile/aad5082f-a261-4dbf-9166-5223a8c88784/source 500 (INTERNAL SERVER ERROR)

Visiting the URL directly led to exactly the same thing.

**Comment by skullydazed** [comment]
There's an operational problem with minio, our internal storage engine. I'm trying to figure it out now.

**Comment by skullydazed** [comment]
This has been fixed for a couple weeks, sorry I never got back here to update the issue.

**Comment by ForsakenHarmony** [comment]
still seems to be happening
