### ISSUE TITLE
Chibios compiling

### ISSUE THREAD

**Issue by yiancar** [qmk/qmk_api#29]
The backend does not support pulling the necessary git modules. For example Chibios, Chibios-Contrib etc. I imagine there should be a way for periodically to check those repos and pull when needed.

As informed by @yanfali the front end can download .bin files and therefore this is in theory the only change needed to support STM32 boards.

I would consider this relatively critical to the support of STM32 based boards as most end users don't want to manually compile there firmware.

**Comment by yiancar** [comment]
We can close his now?:)

**Comment by skullydazed** [comment]
Yup, this is working now. :D
