### ISSUE TITLE
[Bug] Download FULL SOURCE (qmk configurator)

### ISSUE THREAD

**Issue by trebsoj** [qmk/qmk_api#50]
## Describe the Bug
At the time of downloading the file (FULL SOURCE), from qmk configurator, the following error appears:

**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

bm40hsrgb_layout_planck_mit_mine.json: [https://pastebin.com/raw/45wrWR0f](url)

## System Information

 - Keyboard:  bm40hsrgb

**Comment by skullydazed** [comment]
Not sure what's going on but I'll dig into this soon.

**Comment by git-brandon** [comment]
Thanks

**Comment by BillGr7** [comment]
In case it's not happening across the board, just chiming in to say I saw this issue when trying to download source code after compiling handwired/dactyl_manuform/5x6

**Comment by skullydazed** [comment]
Hi folks. This should be fixed as soon as I'm able to deploy a new version of the compiler. Probably 1-2 hours from the time of this message.
